;<?php
;/*
[configBD]
db_driver="mysql"
db_host="localhost"
db_name="timetracker"
db_admin_user="TT_admin"
db_admin_pwd="laSFn0n_cj2n8jbM"
db_user_user="TT_user"
db_user_pwd="KljW92_8"
db_anom_user="TT_anonymous"
db_anom_pwd="aoQ9mX7_"
;?>